export const INPUT_CHANGE = 'INPUT_CHANGE';
export const REGISTRATION_INPUT_CHANGE = 'REGISTRATION_INPUT_CHANGE';
export const GAMES_REGISTRATION_FAILURE = 'GAMES_REGISTRATION_FAILURE';
export const GAMES_REGISTRATION_SUCCESS = 'GAMES_REGISTRATION_SUCCESS';
export const CLEAR_REGISTRATION_FORM  = 'CLEAR_REGISTRATION_FORM';
export const CHECK_BOXES_CHANGE = 'CHECK_BOXES_CHANGE';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_FORM = 'CLEAR_FORM';

export const GET_REGISTERED_USERS = 'GET_REGISTERED_USERS';
export const REDIRECT = 'REDIRECT';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';



